audit_map = {
    'AUDIT - CLIENT/USER CHANGE': 'Audit',
    'AUDIT - EMAIL/TEXT': 'Audit',
    'AUDIT - EMAIL/TEXT RECV': 'Audit',
    'CIRT': 'CIRT',
    'CLIENT REQUEST - CLIENT ID CHANGE': 'ClientID Change',
    'CLIENT REQUEST - CLIENT MERGE': 'Client Merge',
    'CLIENT REQUEST - P2Q': 'P2Q',
    'CLIENT REQUEST - P2Q LDAP': 'P2Q',
    'CLIENT REQUEST - ZERO DOWN': 'ZeroDown',
    'COMM HUB': 'CommHub',
    'ENTERPRISE SEARCH': 'Search',
    'FED - CERT UPDATE': 'Federation',
    'FED - DASHBOARD ISSUE': 'Federation',
    'FED - DE-PROVISIONING': 'Federation',
    'FED - IDP MIGRATION': 'Federation',
    'FED - LOGIN ISSUE': 'Federation',
    'FED - MOBILE': 'Federation',
    'FED - NEW SETUP': 'Federation',
    'FED - PID UPDATE': 'Federation',
    'FED - PROVISIONING ISSUE': 'Federation',
    'FED - SETUP ISSUE': 'Federation',
    'FEDERATION - @ADP USER': 'Federation',
    'FEDERATION - DASHBOARD': 'Federation',
    'FEDERATION - PROVISION': 'Federation',
    'FEDERATION - CERT UPDATE': 'Federation',
    'FEDERATION - LOGIN ISSUE': 'Federation',
    'GWSE': 'GWSE',
    'HELP DESK - AOID CONSOLIDATION': 'AOID Consolidation',
    'HELP DESK - AOID CONSOLIDATION HELP': 'AOID Consolidation',
    'HELP DESK - AOID PURGE': 'AOID Purge',
    'HELP DESK - ENABLE 2FA': 'Enable 2FA',
    'INTERNAL - ACCESS REQUEST': 'Access Request',
    'INTERNAL - OID PURGES': 'OID Purge',
    'INTERNAL - RESEARCH': 'Research',
    'KNOWLEDGE GAP - HELP DESK': 'Knowledge Gap',
    'KNOWLEDGE GAP - SMS': 'Knowledge Gap',
    'LDAP - DATA COMPARISON': 'Report',
    'LDAP - DATA RESTORE': 'Data Restore',
    'N/A': 'N/A',
    '-': 'N/A',
    'GSSO - FED': 'GSSO',
    'GSSO - ACTIVATE UID': 'GSSO',
    'OLP - DATA SYNC': 'OLP',
    'OLP - LOGIN ISSUES': 'OLP',
    'OLP - SHARED CONTACT': 'OLP',
    'OTHER - EXISTING DE': 'Existing DE',
    'OTHER - NTF': 'NTF',
    'OTHER - OTHER': 'Other',
    'PROVISION/DEPROV EES': 'Prov/DeProv EE',
    'REGISTRY - DATA RESTORE': 'Data Restore',
    'REPORT - CLIENT': 'Report',
    'REPORT - INTERNAL': 'Report',
    'SERVER': 'Server',
    'SITEMINDER': 'Siteminder',
    'SSR - BEV ISSUE': 'SSR',
    'SSR - DELETE PIC': 'SSR',
    'SSR - KBA LOCK': 'SSR',
    'SSR - PRC ISSUE': 'SSR',
    'SSR - SIV ISSUE': 'SSR',
    'SSR - SOCURE': 'SSR',
    'STEPUP - AUDIT': 'Audit',
    'STEPUP - OTP NOT REC\'D': 'Step Up',
    'STEPUP - OTP NOT REC': 'Step Up',
    'UTILITY - BULKASSOCIATEUPDATE': 'Utility',
    'UTILITY - DELETE AZSCHEMA': 'Utility',
    'UTILITY - PRODUCT/PROFILE': 'Utility',
    'UTILITY - EXECUTESQL': 'Utility',
    'WEBSERVICE': 'WebService'
}