audit_map = {
    'Audit - client/user change': 'Audit',
    'Audit - email/text': 'Audit',
    'CIRT': 'CIRT',
    'Client Request - Client ID Change': 'ClientID Change',
    'Client Request - Client Merge': 'Client Merge',
    'Client Request - P2Q': 'P2Q',
    'Client Request - Zero Down': 'ZeroDown',
    'Enterprise Search': 'Search',
    'Fed - Cert Update': 'Federation',
    'Fed - Dashboard Issue': 'Federation',
    'Fed - De-Provisioning': 'Federation',
    'Fed - IDP Migration': 'Federation',
    'Fed - Login Issue': 'Federation',
    'Fed - Mobile': 'Federation',
    'Fed - New Setup': 'Federation',
    'Fed - PID Update': 'Federation',
    'Fed - Provisioning Issue': 'Federation',
    'Fed - Setup Issue': 'Federation',
    'GWSE': 'GWSE',
    'Help Desk - AOID Consolidation': 'AOID Consolidation',
    'Help Desk - AOID Purge': 'AOID Purge',
    'Help Desk - Enable 2FA': 'Enable 2FA',
    'Internal - Access Request': 'Access Request',
    'Internal - OID Purges': 'OID Purge',
    'Internal - Research': 'Research',
    'Knowledge Gap - Help Desk': 'Knowledge Gap',
    'Knowledge Gap - SMS': 'Knowledge Gap',
    'LDAP - Data Comparison': 'Report',
    'LDAP - Data Restore': 'Data Restore',
    'N/A': 'N/A',
    '-': 'N/A',
    'GSSO - Fed': 'GSSO',
    'GSSO - Activate UID': 'GSSO',
    'OLP - Data sync': 'OLP',
    'OLP - Login issues': 'OLP',
    'OLP - Shared Contact': 'OLP',
    'Other - Existing DE': 'Existing DE',
    'Other - NTF': 'NTF',
    'Other - Other': 'Other',
    'Provision/Deprov EEs': 'Prov/DeProv EE',
    'Registry - Data Restore': 'Data Restore',
    'Report - Client': 'Report',
    'Report - Internal': 'Report',
    'Server': 'Server',
    'Siteminder': 'Siteminder',
    'SSR - BEV Issue': 'SSR',
    'SSR - Delete PIC': 'SSR',
    'SSR - KBA Lock': 'SSR',
    'SSR - PRC Issue': 'SSR',
    'SSR - SIV Issue': 'SSR',
    'SSR - Socure': 'SSR',
    'StepUp - Audit': 'Audit',
    'StepUp - OTP not rec\'d': 'Step Up',
    'StepUp - OTP not rec': 'Step Up',
    'Utility - BulkAssociateUpdate': 'Utility',
    'Utility - Delete AZSchema': 'Utility',
    'Utility - Product/Profile': 'Utility',
    'Utility - ExecuteSQL': 'Utility',
    'WebService': 'WebService'
}
